sudo: false
language: ruby
rvm:
  - 2.2.7
  - 2.3.1
before_install: gem install bundler -v 1.12.5
env:
  - SLUG_LOCALE_COLUMN=true RAILS_VERSION=5.0
  - SLUG_LOCALE_COLUMN=false RAILS_VERSION=5.0
  - SLUG_LOCALE_COLUMN=true RAILS_VERSION=5.1
  - SLUG_LOCALE_COLUMN=false RAILS_VERSION=5.1
  - SLUG_LOCALE_COLUMN=true RAILS_VERSION=5.2
  - SLUG_LOCALE_COLUMN=false RAILS_VERSION=5.2
